#!/bin/bash
source scripts/colors
source scripts/aws_iam_mgr
source scripts/aws_s3_mgr

clear

# Print AWSMGR Header
echo -e "${BOLD}${CYAN}==============================================${RESET}"
echo -e "${BOLD}${BLUE}              AWSMGR - AWS CLI Manager        ${RESET}"
echo -e "${BOLD}${CYAN}==============================================${RESET}"
echo -e "${GREEN}🚀 Manage ALL AWS CLI functionalities in one place!${RESET}"
echo ""

while true; do
    echo "
    Which Service you want to use?
    1) IAM
    2) EC2
    3) S3
    4) Exit"

    read -p "Choose: " main_num

    case $main_num in
        1) aws_iam_mgr;;
        2) echo "Test 2";;
        3) aws_s3_mgr;;
        4) echo "Exiting...";break;;
        *) echo "Invalid Input"
    esac
done