#!/bin/bash

source scripts/iam/aws_iam_list_users

function aws_iam_delete_user()
{
    aws_iam_list_users
    echo""
    read -p " Enter username you want to delete: " iam_username
    output=$(aws iam delete-user --user-name "$iam_username" 2>&1)  
    if echo "$output" | grep -q "NoSuchEntity"; then
        echo -e "${BOLD}${RED}Error: User '$iam_username' doesn't exist!${RESET}"
    elif [ -z "$output" ]; then
        echo -e "${BOLD}${GREEN}User '$iam_username' deleted successfully!${RESET}"
    else
        echo -e "${BOLD}${YELLOW}Unexpected error occurred:${RESET}"
        echo "$output"
    fi

}