#!/bin/bash

function aws_iam_user_initial_password()
{
    aws_iam_list_users

    read -p "Enter Username you want to set update password" username

    if [[ -z "$username" ]]; then
        echo -e "Please Enter a valid name"
        return
    fi

    read -p "Enter new password for the user $username" passwdd



}