#!/bin/bash

function aws_iam_user_update_password() {
    aws_iam_list_users

    echo -e "Enter Username you want to update the password for:"
    read -p "> " username

    if [[ -z "$username" ]]; then
        echo -e "${RED}Error: Please enter a valid username.${RESET}"
        return
    fi

    echo -e "Enter new password for the user '$username':"
    read -p "> " passwdd

    if [[ -z "$passwdd" ]]; then
        echo -e "${RED}Error: Please enter a valid password.${RESET}"
        return
    fi

    # Update login profile (password)
    output=$(aws iam update-login-profile --user-name "$username" --password "$passwdd" 2>&1)
    if [[ $? -eq 0 ]]; then
        echo -e "${GREEN}✔️ User password updated successfully!${RESET}"
    else
        echo -e "${RED}❌ Error occurred while updating password:${RESET}"
        echo "$output"
        return
    fi

    # Ask if user wants to save credentials
    echo -e "Do you want to save the credentials to a file? (y/n)"
    read -p "> " chose

    if [[ "$chose" == "y" ]]; then
        credentials_dir="/home/$USER/.config/awsmgr/user_credentials"
        mkdir -p "$credentials_dir"

        {
            echo "username: $username"
            echo "password: $passwdd"
        } > "$credentials_dir/$username.txt"

        echo -e "${GREEN}✔️ Credentials saved at ${BOLD}$credentials_dir/$username.txt${RESET}"
    fi

    echo -e "${CYAN}${BOLD}Generated Credentials:${RESET}"
    echo -e "Username: ${BOLD}$username${RESET}"
    echo -e "Password: ${BOLD}$passwdd${RESET}"
}
