#!/bin/bash

function aws_iam_user_initial_password() {
    aws_iam_list_users

    echo -e "${CYAN}${BOLD}Enter Username you want to set initial password:${RESET}"
    read -p "> " username

    if [[ -z "$username" ]]; then
        echo -e "${RED}Error: Please enter a valid username.${RESET}"
        return
    fi

    echo -e "${CYAN}${BOLD}Enter password for the user $username:${RESET}"
    read -s -p "> " passwdd
    echo ""

    if [[ -z "$passwdd" ]]; then
        echo -e "${RED}Error: Please enter a valid password.${RESET}"
        return
    fi

    echo -e "${CYAN}${BOLD}Allow user to reset password during first login? (y/n):${RESET}"
    read -p "> " choose

    if [[ "$choose" == "y" ]]; then
        output=$(aws iam create-login-profile --user-name "$username" --password "$passwdd" --password-reset-required 2>&1)
    else
        output=$(aws iam create-login-profile --user-name "$username" --password "$passwdd" 2>&1)
    fi

    if echo "$output" | grep -q '"UserName"\|"CreateDate"\|"PasswordResetRequired"'; then
        echo -e "${GREEN}✔️ User password created successfully!${RESET}"
    else
        echo -e "${RED}❌ Error occurred while creating password:${RESET}"
        echo "$output"
        return
    fi

    echo -e "${YELLOW}${BOLD}Would you like to save $username's credentials? (y/n):${RESET}"
    read -p "> " chose

    if [[ "$chose" == "y" ]]; then
        credentials_dir="/home/$USER/.config/awsmgr/user_credentials"
        mkdir -p "$credentials_dir"

        {
            echo "username: $username"
            echo "password: $passwdd"
        } > "$credentials_dir/$username.txt"

        echo -e "${GREEN}✔️ Credentials saved at ${BOLD}$credentials_dir/$username.txt${RESET}"
    fi

    echo -e "${CYAN}${BOLD}Generated Credentials:${RESET}"
    echo -e "Username: ${BOLD}$username${RESET}"
    echo -e "Password: ${BOLD}$passwdd${RESET}"
}
