#!/bin/bash

#colors
source scripts/colors

source scripts/s3/aws_s3_create_bucket

function aws_s3_mgr()
{
    while true; do
        echo -e "${GREEN}---------------------------------${RESET}"
        echo -e "${BOLD}1) Create S3 Bucket${RESET}"

        read -p "choose an option: " s3_num

        case $s3_num in
            1)
            aws_s3_create_bucket
            ;;
            *)
            echo "Invalid Input"
            sleep 1
            ;;
        esac
    done    

}