#!/bin/bash

#colors
source scripts/colors

source scripts/s3/aws_s3_create_bucket
source scripts/s3/aws_s3_list_bucket
source scripts/s3/aws_s3_delete_bucket
source scripts/s3/aws_s3_list_bucket_objects


function aws_s3_mgr()
{
    while true; do
        echo -e "${GREEN}---------------------------------${RESET}"
        echo -e "${BOLD}1) Create S3 Bucket${RESET}"
        echo -e "${BOLD}2) List S3 Buckets${RESET}"
        echo -e "${BOLD}3) Delete S3 Bucket${RESET}"
        echo -e "${BOLD}4) List S3 Bucket Objects${RESET}"
        echo -e "${BOLD}5) Exit ${RESET}"


        read -p "choose an option: " s3_num

        case $s3_num in
            1)
            aws_s3_create_bucket
            ;;
            2)
            aws_s3_list_bucket
            ;;
            3)
            aws_s3_delete_bucket
            ;;
            4)
            aws_s3_list_bucket
            aws_s3_list_bucket_objects
            ;;
            5)
            break
            ;;
            *)
            echo "Invalid Input"
            sleep 1
            ;;
        esac
    done    

}